#서버 포트 설정
server:
  host : https://pyeonhang.world/  #나중에 AWS도메인으로변경
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
      force-request: true
      force-response: true
  port: 9090 #나중에 AWS포트로변경
  file:
    upload:
      path: C:\\files\\upload\\board\\
    coupon:
      path: C:\\files\\upload\\coupon\\


spring:
  main:
    allow-bean-definition-overriding: true
  jwt:
    secretKey : t0MNxZCdjr1vQbxqMMhMsOkdsuHNavb76OOSjktWDGp
  mail:
    host: smtp.gmail.com
    port: 587
    username: hcandhb@gmail.com
    password: fydm tfcl cang smkz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
           protocols: TLSv1.2
           trust:  smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?
  cache:
    type: simple

  #Database 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://pyeonhang-db.cjg402amekn6.ap-southeast-2.rds.amazonaws.com/pyeonhang
    username: root
    password: goqlsgoqls1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 10000
      data-source-properties:
        cachePrepStmts : true #캐쉬 설정 on 
        prepStmtCacheSize : 250 #문서 할당 수
        prepStmtCacheSqlLimit: 2048 #sql 최대길이 byte 단위
        useServerPrepStmts: true # 최신기능 지원설정 on


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate #개발환경에서는 update, 보통 validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        use_sql_comments: false
        cache:
          use_sql_comments: false
          use_query_cache: false



  #코드 수정 시 자동으로 컴파일 & 적용
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
    restart:
      enabled: true

#로그 설정
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO
      thymeleaf: OFF
      hibernate:
        SQL : debug
        type:
          descriptor:
            sql : trace
  config : #classpath:logb ack.xml

# 이미지 클라우드
cloudinary:
  cloud_name: dmmb3enay
  api_key: 816594852459833
  api_secret: 4uScSdblDA2pGsPoURHZjuDzLO4